
batch_size: 64
epochs: 80
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False
ckpt: checkpoint
loss_func: split_view
state: train
model:
  out_dim: 256
  base_model: "vgg16"

dataset:
  s: 1
  input_shape: (96,96,3)
  num_workers: 0
  valid_size: 0.05

loss:
  temperature: 0.5
  use_cosine_similarity: False

split_at:
  channels: 512
  radix: 2
  cardinality: 2
  reduction_factor: 4
  at_map: True

earlystopping:
  patience: 7
  delta: 0